### ISSUE TITLE
error: unknown command "klock" for "kubectl"

### ISSUE THREAD

**Issue by arthurzenika** [jilleJr/kubectl-klock#16]
After installing klock using krew I get 

```
$ kubectl klock pods
error: unknown command "klock" for "kubectl"
```
I have plenty of other plugins working, so I don't think it's a problem with my krew configuration

```
$ kubectl krew install klock
Updated the local copy of plugin index.
Installing plugin: klock
W0503 13:57:57.625379  368660 install.go:160] Skipping plugin "klock", it is already installed
```

**Comment by jilleJr** [comment]
Hello! Thanks for posting this.

I've only tested this on my own computer, and well, _it works on my machine_

Your command output does say it is already installed. So somehow krew finds it, but not your shell. Maybe it got renamed wrong? Maybe it doesn't have execute permissions set?

Mind you sharing the following?

1. OS (Windows? Mac? Linux? WSL?)

2. Architecture? (AMD64? ARM?)

3. Shell (bash? zsh?)

4. Outputs from the following commands:
   ```bash
   printenv PATH

   which -a kubectl-klock

   kubectl krew list

   kubectl plugin list

   # Replace path with wherever you have your krew plugins stored.
   # By default, it should be as below:
   ls -alh ~/.krew/bin
   ```

**Comment by arthurzenika** [comment]
Hi, thanks for getting back to me about this problem. With your commands I found what was going wrong, it's a missing element in my path since I have installed krew using asdf. Installing with `kubectl krew install klock -v 9` enabled me to see where the binary was put. Closing this issue.
