### ISSUE TITLE
Support for filtering resources by text

### ISSUE THREAD

**Issue by semihbkgr** [jilleJr/kubectl-klock#31]
Do you have any plan to filter resources in the table by text?

I took a look at the source code, and I saw some code related to filtering which are commented out.

**Comment by jilleJr** [comment]
Hello! Yes, that's the plan. I never quite got around to it though.

The bubbletea "list" package has a nice searching implementation, where you press "/" and then the header row becomes the search field. Hiding the column names just for a short while turns out to be just fine
